In [1]:
!pip install datasets

In [2]:
from datasets import load_dataset

In [3]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})


In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rat

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df=df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [11]:
# Reduce the no of rows
df=df.head(15000)
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th..."
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...


In [12]:
df.isnull().sum()

,0
title,0
abstract,0


In [13]:
df["paper_text"]=df["title"]+" "+df["abstract"]
df

/tmp/ipykernel_2791/3936252372.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]


,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...


In [14]:
# // converting into dataframe
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [15]:
type(df[["paper_text"]].head())

pandas.core.frame.DataFrame

In [16]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regress

In [17]:
from sentence_transformers import SentenceTransformer

In [18]:
# 1. Load a pretrained Sentence Transformer model

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [19]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [20]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparam

In [21]:
# Remove \n(new line) so that model does not become confuse with \n
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df

/tmp/ipykernel_2791/1813364570.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)


,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...


In [22]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [23]:
# Removed white spaces in front and last
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_2791/1640325731.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()


In [24]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [25]:
# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sample_text)
print(embeddings.shape)
print(type(embeddings))

(384,)
<class 'numpy.ndarray'>


In [26]:
embeddings

array([-1.31564096e-01, -6.78266399e-03, -3.67611554e-03,  3.26515771e-02,
        1.12196416e-01,  1.22726746e-02,  9.81671885e-02, -9.00522992e-02,
        4.23116125e-02, -1.97734833e-02, -3.30841690e-02,  7.45294765e-02,
        1.06320381e-01, -2.06042901e-02, -2.05210559e-02,  1.69492734e-03,
        7.08195344e-02,  5.85445389e-02, -1.12319119e-01,  2.08247416e-02,
        5.69254383e-02,  2.01577954e-02,  2.58310959e-02,  3.21703032e-02,
        1.05137639e-01, -9.67676342e-02,  2.70080194e-02, -2.34509036e-02,
       -4.54967804e-02, -1.01369917e-02, -1.79485492e-02, -4.81442735e-02,
        1.07765235e-02, -3.75906937e-02,  1.94348078e-02,  3.71518917e-02,
        2.96784397e-02,  4.33094054e-02,  4.37321328e-02,  3.70486639e-02,
       -1.82594243e-03,  4.55183210e-03, -7.99066573e-03,  3.03736813e-02,
       -1.43779954e-02,  3.79514731e-02,  5.95915988e-02, -2.58335639e-02,
       -6.52157590e-02,  5.90026751e-02, -2.10713428e-02,  7.35942200e-02,
       -5.72010614e-02,  

In [27]:
embeddings[:16]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493], dtype=float32)

In [28]:
# top 5 lekar usko list meh convert kar diya
sample_embedding=model.encode(df["paper_text"].head(5).to_list())
sample_embedding

array([[-0.1315641 , -0.00678266, -0.0036761 , ...,  0.09561252,
        -0.04423944,  0.00522624],
       [-0.03589668, -0.06343269, -0.00394966, ...,  0.07206137,
        -0.13262011, -0.00412079],
       [-0.08129284,  0.024103  , -0.08868261, ..., -0.04524419,
        -0.0476585 , -0.01549932],
       [-0.10218991, -0.06282566,  0.03273673, ..., -0.03118814,
         0.03174181,  0.03621249],
       [-0.08391042,  0.01838467, -0.01556663, ..., -0.01188403,
        -0.10644462,  0.00790998]], dtype=float32)

In [29]:
print(sample_embedding.shape)

(5, 384)


#Analysis

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
# Cosine similarity expects 2D
# Here reshape(1,-1) --> take 1 row and adjust the columns to the remaining ones
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
similarity

array([[1.0000001]], dtype=float32)

In [33]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
similarity

array([[0.36625272]], dtype=float32)

In [34]:
# Calculating similarity for first 5
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]


#Generating the Embeddings for 15000

In [36]:
#Embeddings-->Batch Size-->Ram Consumption Less
embedding=model.encode(df["paper_text"].to_list(),batch_size=32,show_progress_bar=True)

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

In [37]:
print(embedding.shape)
print(type(embedding))
print(embedding.dtype)

(15000, 384)
<class 'numpy.ndarray'>
float32


FAISS --> It creates a special search structure

Cosine Similarity --> dot product hota hai

FAISS --> Inner product hota hai

L2 Normalization

In [38]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 39.2 MB/s eta 0:00:00


In [39]:
import faiss

In [40]:
# Normalise embedding
faiss.normalize_L2(embedding)

In [41]:
# Create index
# Here IP means Inner Product it means it creates inner product for all embeddings
index=faiss.IndexFlatIP(384)
index

<faiss.swigfaiss.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x7ae5f226e1b0> >

In [43]:
# Add the L2 normalized embeddings to the FAISS index.
# This prepares the index for efficient similarity searches.
index.add(embedding)

In [44]:
print(index.ntotal)

30000


In [45]:
# Create embedding for a query
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
print(query_embedding.shape)

(1, 384)


In [46]:
# Normalize the query_embedding
faiss.normalize_L2(query_embedding)

In [47]:
# To search how closely our query matches with the stored vectors of the research papers
D,I=index.search(query_embedding,5)
print(D) # Similarity Score --> tells us the similarity score between our query nd the reseach papers stored in the FAISS
print(I) # Indices --> It tells konse paper no seh it is similar

[[0.6807244  0.6807244  0.67092204 0.67092204 0.65219975]]
[[25466 10466 28730 13730 26873]]
